language: php

# list any PHP version you want to test against
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0
#  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
#  - travis_retry composer install symfony/yaml

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

#after_script:
#  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
